### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by AndreasFromDanmark** [james12007/qb-sheriffjob-main#1]
Can you fix this? getting the same error on Sheriff and sasp job for QBCore

![image](https://user-images.githubusercontent.com/35656492/169718728-2a6284a3-ec94-40b0-a3eb-557bc7f21b95.png)

**Comment by james12007** [comment]
> Can you fix this? getting the same error on Sheriff and sasp job for QBCore
> 
> ![image](https://user-images.githubusercontent.com/35656492/169718728-2a6284a3-ec94-40b0-a3eb-557bc7f21b95.png)

can u join my discord, it will be good there

**Comment by cory86randal** [comment]
Im having the same issue in same file line 142

**Comment by james12007** [comment]
Can u plz join my discord server
It will be easy to solve this issue

JAMES

**Comment by LividDS** [comment]
I'm having this same issue, what's your discord?

**Comment by james12007** [comment]
All issues Fixed now
